// AltWallet — shared data constants

export const LOGO_URL = "/logo-altwallet.png";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const HERO_ORB_URL = "/manus-storage/hero-orb_ca496551.png";

export type ChainCode = "ETH" | "BTC" | "SOL" | "TRX" | "XRP" | "SUI";

export interface ChainInfo {
  code: ChainCode;
  name: string;
  color: string;
  beta: boolean;
  placeholder: string;
}

export const CHAINS: ChainInfo[] = [
  { code: "ETH", name: "Ethereum", color: "#627EEA", beta: false, placeholder: "0x…" },
  { code: "BTC", name: "Bitcoin", color: "#F7931A", beta: false, placeholder: "bc1… or 1…" },
  { code: "SOL", name: "Solana", color: "#9945FF", beta: false, placeholder: "Base58 address" },
  { code: "TRX", name: "Tron", color: "#FF0013", beta: false, placeholder: "T…" },
  { code: "XRP", name: "XRP Ledger", color: "#00AAE4", beta: true, placeholder: "r…" },
  { code: "SUI", name: "Sui", color: "#4DA2FF", beta: true, placeholder: "0x…" },
];

export const CHAIN_MAP: Record<ChainCode, ChainInfo> = CHAINS.reduce(
  (acc, c) => ({ ...acc, [c.code]: c }),
  {} as Record<ChainCode, ChainInfo>
);

export type RiskTone = "safe" | "medium" | "high";

export function riskFromScore(score: number): { tone: RiskTone; label: string } {
  if (score >= 70) return { tone: "safe", label: "Safe" };
  if (score >= 40) return { tone: "medium", label: "Medium Risk" };
  return { tone: "high", label: "High Risk" };
}

export const WHOP_PRO_URL = "https://whop.com/altneurealms/altwallet-pro";
export const WHOP_BUSINESS_URL = "https://whop.com/altneurealms/altwallet-business";

// ---------- Demo scan dataset ---------------------------------------------
// These scans are deterministic demo data used by the Checker flow so the UI
// feels alive without a backend.

export interface ScanResult {
  address: string;
  chain: ChainCode;
  score: number;
  delta: number;
  walletAge: string;
  txCount: number;
  totalVolume: string;
  counterparties: number;
  redFlags: RiskFlag[];
  yellowFlags: RiskFlag[];
  greenSignals: RiskFlag[];
  txHistory: TxRow[];
  aiSummary: string;
  exposure: string;
  activeApprovals: number;
  lastActivity: string;
}

export interface RiskFlag {
  id: string;
  title: string;
  detail: string;
}

export interface TxRow {
  date: string;
  type: string;
  amount: string;
  token: string;
  counterparty: string;
  chain: ChainCode;
  risk?: RiskTone;
}

export const EXAMPLE_ADDRESSES: Record<ChainCode, string> = {
  ETH: "0x7a3f4b2cde918f2c88f09a7b4ce4e91c2b3de8a1",
  BTC: "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh",
  SOL: "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM",
  TRX: "TNPeeaaFB7K9cmo4uQpcU32zGK8G1NYqeL",
  XRP: "rLNaPoKeeBjZe2qs6x52yVPZpZ8td4dc6w",
  SUI: "0xdee9e5b0e5c5e3c2c3e7a9d1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1",
};

// Simple deterministic hash so each address always gets the same score
function hashString(input: string): number {
  let h = 5381;
  for (let i = 0; i < input.length; i++) {
    h = ((h << 5) + h) ^ input.charCodeAt(i);
  }
  return Math.abs(h);
}

export function generateScan(address: string, chain: ChainCode): ScanResult {
  const h = hashString(address.toLowerCase() + chain);
  // Score 15..95 with some bias toward the higher range for demo
  let score = 20 + (h % 76);
  if (score > 95) score = 95;
  // Apply XRP/SUI 0.8x + cap at 80 per spec
  if (chain === "XRP" || chain === "SUI") {
    score = Math.min(80, Math.round(score * 0.8));
  }
  const tone = riskFromScore(score).tone;

  const redPool: RiskFlag[] = [
    { id: "mixer", title: "Mixer / tumbler interaction", detail: "This wallet has transacted with a known coin mixer. Mixers are commonly used to obscure the origin of funds and are a strong indicator of high-risk activity." },
    { id: "drain", title: "Rapid fund drain", detail: "More than 80% of the wallet's balance moved out within a 24-hour window. This pattern is frequently associated with compromised or scam wallets cashing out." },
    { id: "sanctioned", title: "Sanctioned counterparty", detail: "This wallet has interacted with an address on OFAC or other sanctions lists. Transacting with sanctioned entities may have legal consequences in your jurisdiction." },
    { id: "wash", title: "Wash trading detected", detail: "Transaction patterns suggest artificial volume generated by repeated self-trading between controlled wallets." },
  ];
  const yellowPool: RiskFlag[] = [
    { id: "new", title: "New wallet (under 30 days)", detail: "This wallet was created less than 30 days ago. Young wallets carry more uncertainty because there is little history to evaluate." },
    { id: "burst", title: "Burst activity", detail: "A large number of transactions occurred within a short time window — this may be normal trading, but it also overlaps with automated bot or drainer behaviour." },
    { id: "fanout", title: "Fan-out pattern", detail: "Funds were split and forwarded to many different addresses in rapid succession, which can sometimes indicate layering." },
  ];
  const greenPool: RiskFlag[] = [
    { id: "cex", title: "Known exchange counterparty", detail: "Wallet has directly transacted with a reputable centralised exchange, suggesting it belongs to a KYC'd user." },
    { id: "age", title: "Wallet older than 1 year", detail: "Long-lived wallets with consistent activity are generally less risky." },
    { id: "diverse", title: "Diverse counterparties", detail: "Interactions span a wide range of services and peers, reducing the concentration of counterparty risk." },
    { id: "clean", title: "No sanctions matches", detail: "No direct or indirect exposure to sanctioned entities was detected by GoPlus." },
  ];

  const pick = <T,>(arr: T[], n: number, seed: number): T[] => {
    const items: T[] = [];
    for (let i = 0; i < n && i < arr.length; i++) {
      items.push(arr[(seed + i * 7) % arr.length]);
    }
    return items;
  };

  let redFlags: RiskFlag[] = [];
  let yellowFlags: RiskFlag[] = [];
  let greenSignals: RiskFlag[] = [];

  if (tone === "high") {
    redFlags = pick(redPool, 2 + (h % 3), h);
    yellowFlags = pick(yellowPool, 2, h + 1);
    greenSignals = pick(greenPool, 1, h + 2);
  } else if (tone === "medium") {
    redFlags = pick(redPool, 1, h);
    yellowFlags = pick(yellowPool, 2 + (h % 2), h + 1);
    greenSignals = pick(greenPool, 2, h + 2);
  } else {
    yellowFlags = pick(yellowPool, 1, h + 1);
    greenSignals = pick(greenPool, 3, h + 2);
  }

  const tokens = ["ETH", "USDC", "USDT", "WBTC", "LINK", "ARB", "OP"];
  const types = ["Transfer", "Swap · Uniswap V3", "Swap · Curve", "Contract", "Approval", "Bridge"];
  const counters = [
    "0x4b91…c7e2",
    "0xf02a…81dd",
    "0x9e17…2b04",
    "0x33cc…08fa",
    "0xd4a1…55ec",
    "0x1f0b…a231",
    "0x8ac0…e44d",
  ];
  const txHistory: TxRow[] = Array.from({ length: 14 }, (_, i) => {
    const seed = h + i * 13;
    const amt = ((seed % 1200) + 12) / 10;
    const risk: RiskTone = i % 5 === 0 ? "high" : i % 3 === 0 ? "medium" : "safe";
    return {
      date: `${(1 + (i * 3) % 28).toString().padStart(2, "0")} Apr`,
      type: types[seed % types.length],
      amount: amt.toFixed(2),
      token: tokens[seed % tokens.length],
      counterparty: counters[seed % counters.length],
      chain,
      risk,
    };
  });

  const walletAgeMonths = tone === "safe" ? 18 + (h % 24) : tone === "medium" ? 6 + (h % 12) : (h % 45);
  const walletAge =
    walletAgeMonths < 1
      ? `${h % 28 + 1} days`
      : walletAgeMonths < 12
      ? `${walletAgeMonths} months`
      : `${Math.floor(walletAgeMonths / 12)}y ${walletAgeMonths % 12}m`;

  const volume = (20000 + (h % 90000)).toLocaleString();
  const counterpartiesCount = 6 + (h % 48);
  const txCount = 120 + (h % 3200);
  const exposure = "$" + (320 + (h % 9500)).toLocaleString();

  const aiSummary = buildAiSummary(address, chain, score, redFlags, yellowFlags, greenSignals);

  return {
    address,
    chain,
    score,
    delta: ((h % 25) - 12),
    walletAge,
    txCount,
    totalVolume: "$" + volume,
    counterparties: counterpartiesCount,
    redFlags,
    yellowFlags,
    greenSignals,
    txHistory,
    aiSummary,
    exposure,
    activeApprovals: h % 5,
    lastActivity: `${(h % 48) + 1} hours ago`,
  };
}

function buildAiSummary(
  address: string,
  chain: ChainCode,
  score: number,
  red: RiskFlag[],
  yellow: RiskFlag[],
  green: RiskFlag[]
): string {
  const short = address.length > 12 ? `${address.slice(0, 6)}…${address.slice(-4)}` : address;
  const band = riskFromScore(score).label.toLowerCase();
  const issues: string[] = [];
  if (red.length) issues.push(`${red.length} red flag${red.length > 1 ? "s" : ""}`);
  if (yellow.length) issues.push(`${yellow.length} yellow flag${yellow.length > 1 ? "s" : ""}`);
  if (green.length) issues.push(`${green.length} positive signal${green.length > 1 ? "s" : ""}`);

  const headline =
    score >= 70
      ? `Wallet ${short} on ${chain} currently looks ${band}.`
      : score >= 40
      ? `Wallet ${short} on ${chain} shows ${band} — proceed with caution.`
      : `Wallet ${short} on ${chain} scored as ${band}. We recommend avoiding interaction until more evidence is available.`;

  const body =
    red.length > 0
      ? ` The strongest concern is "${red[0].title.toLowerCase()}", which historically correlates with scams or drained wallets.`
      : yellow.length > 0
      ? ` The main thing to watch is "${yellow[0].title.toLowerCase()}", which does not confirm malicious intent on its own but warrants care.`
      : ` No serious red flags were detected across sanctions, mixer, or drain heuristics.`;

  const tail =
    green.length > 0
      ? ` On the positive side, we found ${green.length} supporting signal${green.length > 1 ? "s" : ""} including "${green[0].title.toLowerCase()}".`
      : "";

  const disclaimer = " This is one layer of due diligence, not a guarantee — always cross-check before moving significant value.";

  return headline + body + tail + ` Summary: ${issues.join(", ") || "no notable issues"}.` + disclaimer;
}
